spring:
  application:
    name: blog
  profiles:
    active: prod
  config:
    import: optional:configserver:http://glue-config.glue-service.svc.cluster.local:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

application:
  config:
    auths-url: http://glue-auth.glue-service.svc.cluster.local:8080/auths
    posts-url: http://glue-post.glue-service.svc.cluster.local:8082/posts

jwt:
  secret: ${JWT_SECRET}