name: Glue Blog Server CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login KakaoCloud
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GLUE_PROJECT }}
          username: ${{ secrets.ACCESS_ID }}
          password: ${{ secrets.ACCESS_SECRET }}

      - name: Build and Push to KakaoCloud
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ secrets.GLUE_PROJECT }}/glue-repository/glue-blog:${{ github.sha }}
          build-args: |
            AWS_BUCKET=${{ secrets.AWS_BUCKET }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            AUTH_URL=${{ secrets.AUTH_URL }}
            POST_URL=${{ secrets.POST_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}

  update-manifest-state:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout glue-msa-config repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_PROJECT }}/glue-msa-config
          token: ${{ secrets.GIT_TOKEN}}
          ref: "main"

      - name: Install yq
        run: sudo snap install yq

      - name: Update image in deployment file
        run: |
          yq e '.spec.template.spec.containers[0].image = "${{ secrets.GLUE_PROJECT }}/glue-repository/glue-blog:${{ github.sha }}"' ./k8s-template/blog-deployment.yaml -i

      - name: Commit and Push changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add .
          git commit -m "[skip ci] Update deployment-server.yaml"
          git remote set-url origin https://${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.GIT_PROJECT }}/glue-msa-config
          git push --set-upstream origin main